# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'policedb.ui'
#
# Created: Wed Jan  9 14:40:19 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PoliceDB(object):
    def setupUi(self, PoliceDB):
        PoliceDB.setObjectName("PoliceDB")
        PoliceDB.resize(849, 599)
        self.centralWidget = QtGui.QWidget(PoliceDB)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.suspect_database_tab = QtGui.QWidget()
        self.suspect_database_tab.setObjectName("suspect_database_tab")
        self.label = QtGui.QLabel(self.suspect_database_tab)
        self.label.setGeometry(QtCore.QRect(10, 0, 661, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(48)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtGui.QFrame(self.suspect_database_tab)
        self.line.setGeometry(QtCore.QRect(0, 80, 481, 16))
        self.line.setAcceptDrops(False)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.addNewButton = QtGui.QPushButton(self.suspect_database_tab)
        self.addNewButton.setGeometry(QtCore.QRect(440, 100, 75, 23))
        self.addNewButton.setObjectName("addNewButton")
        self.groupBox = QtGui.QGroupBox(self.suspect_database_tab)
        self.groupBox.setGeometry(QtCore.QRect(520, 80, 291, 521))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 271, 251))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.PrimaryIm = QtGui.QWidget()
        self.PrimaryIm.setObjectName("PrimaryIm")
        self.label_3 = QtGui.QLabel(self.PrimaryIm)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 201, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/new/prefix1/lucasss.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.tabWidget_2.addTab(self.PrimaryIm, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 280, 271, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(70, 30, 58, 15))
        self.label_31.setObjectName("label_31")
        self.nameLabel = QtGui.QLabel(self.groupBox_2)
        self.nameLabel.setGeometry(QtCore.QRect(130, 30, 58, 15))
        self.nameLabel.setObjectName("nameLabel")
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(70, 50, 58, 15))
        self.label_33.setObjectName("label_33")
        self.ageLabel = QtGui.QLabel(self.groupBox_2)
        self.ageLabel.setGeometry(QtCore.QRect(130, 50, 58, 15))
        self.ageLabel.setObjectName("ageLabel")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 380, 271, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.descLabel = QtGui.QLabel(self.groupBox_3)
        self.descLabel.setGeometry(QtCore.QRect(10, 20, 251, 71))
        self.descLabel.setTextFormat(QtCore.Qt.RichText)
        self.descLabel.setObjectName("descLabel")
        self.label_10 = QtGui.QLabel(self.suspect_database_tab)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 371, 16))
        self.label_10.setObjectName("label_10")
        self.imageList = QtGui.QListWidget(self.suspect_database_tab)
        self.imageList.setGeometry(QtCore.QRect(30, 140, 481, 371))
        self.imageList.setViewMode(QtGui.QListView.IconMode)
        self.imageList.setUniformItemSizes(True)
        self.imageList.setObjectName("imageList")
        self.tabWidget.addTab(self.suspect_database_tab, "")
        self.suspect_matching_tab = QtGui.QWidget()
        self.suspect_matching_tab.setObjectName("suspect_matching_tab")
        self.label_4 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(48)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtGui.QFrame(self.suspect_matching_tab)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 521, 16))
        self.line_2.setAcceptDrops(False)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_5.setGeometry(QtCore.QRect(745, -40, 78, 720))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/new/prefix1/vert2.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalScrollBar_2 = QtGui.QScrollBar(self.suspect_matching_tab)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(730, 0, 16, 591))
        self.verticalScrollBar_2.setMinimum(0)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.groupBox_4 = QtGui.QGroupBox(self.suspect_matching_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 100, 321, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 301, 301))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/new/prefix1/mugchar.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.groupBox_5 = QtGui.QGroupBox(self.suspect_matching_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(380, 100, 321, 331))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 301, 301))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/new/prefix1/celeb.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_12.setGeometry(QtCore.QRect(170, 450, 101, 101))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000000.bmp"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_13.setGeometry(QtCore.QRect(310, 450, 101, 101))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000060.bmp"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_14.setGeometry(QtCore.QRect(450, 450, 101, 101))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000160.bmp"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_15.setGeometry(QtCore.QRect(590, 450, 101, 101))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000225.bmp"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_11 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_11.setGeometry(QtCore.QRect(20, 490, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_16 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_16.setGeometry(QtCore.QRect(20, 460, 131, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_17.setGeometry(QtCore.QRect(20, 510, 121, 16))
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.suspect_matching_tab, "")
        self.hopfiel_playground_tab = QtGui.QWidget()
        self.hopfiel_playground_tab.setObjectName("hopfiel_playground_tab")
        self.label_8 = QtGui.QLabel(self.hopfiel_playground_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 771, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(48)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_3 = QtGui.QFrame(self.hopfiel_playground_tab)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 521, 16))
        self.line_3.setAcceptDrops(False)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_6 = QtGui.QGroupBox(self.hopfiel_playground_tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 100, 791, 131))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 101, 101))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/smiley1.bmp.bmp"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(280, 20, 101, 101))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/eleven.bmp.bmp"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(150, 20, 101, 101))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/plus.bmp.bmp"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(410, 20, 101, 101))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/house.bmp.bmp"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(540, 20, 101, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/circle.bmp.bmp"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(670, 20, 101, 101))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/squarecross.bmp.bmp"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.groupBox_7 = QtGui.QGroupBox(self.hopfiel_playground_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 321, 311))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 291, 281))
        self.label_9.setCursor(QtCore.Qt.ArrowCursor)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/new/prefix1/drawn-circle.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.groupBox_8 = QtGui.QGroupBox(self.hopfiel_playground_tab)
        self.groupBox_8.setGeometry(QtCore.QRect(340, 240, 461, 311))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setGeometry(QtCore.QRect(20, 30, 61, 61))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000001.bmp.bmp"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(90, 30, 61, 61))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000004.bmp.bmp"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.groupBox_8)
        self.label_26.setGeometry(QtCore.QRect(160, 30, 61, 61))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000006.bmp.bmp"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(230, 30, 61, 61))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000008.bmp.bmp"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtGui.QLabel(self.groupBox_8)
        self.label_28.setGeometry(QtCore.QRect(300, 30, 61, 61))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000009.bmp.bmp"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtGui.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(370, 30, 61, 61))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000010.bmp.bmp"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtGui.QLabel(self.groupBox_8)
        self.label_30.setGeometry(QtCore.QRect(20, 90, 411, 221))
        self.label_30.setTextFormat(QtCore.Qt.RichText)
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.hopfiel_playground_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        PoliceDB.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(PoliceDB)
        self.statusBar.setObjectName("statusBar")
        PoliceDB.setStatusBar(self.statusBar)

        self.retranslateUi(PoliceDB)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PoliceDB)

    def retranslateUi(self, PoliceDB):
        PoliceDB.setWindowTitle(QtGui.QApplication.translate("PoliceDB", "PoliceDB", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PoliceDB", "Suspect Database", None, QtGui.QApplication.UnicodeUTF8))
        self.addNewButton.setText(QtGui.QApplication.translate("PoliceDB", "Add New", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PoliceDB", "Selected suspect", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.PrimaryIm), QtGui.QApplication.translate("PoliceDB", "Primary Image", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QtGui.QApplication.translate("PoliceDB", "Secondary Image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PoliceDB", "Person", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("PoliceDB", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("PoliceDB", "Lucas S.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("PoliceDB", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.ageLabel.setText(QtGui.QApplication.translate("PoliceDB", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PoliceDB", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.descLabel.setText(QtGui.QApplication.translate("PoliceDB", "<html><head/><body><p>A highly suspicious criminal with a<br/>dark history.</p><p>Seen primarily at night in libraries.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PoliceDB", "The following images are trained into the database:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.suspect_database_tab), QtGui.QApplication.translate("PoliceDB", "Suspect Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PoliceDB", "Suspect Matching", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PoliceDB", "Input image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PoliceDB", "Best matching image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PoliceDB", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("PoliceDB", "Convergence chain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("PoliceDB", "Hopfield model:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.suspect_matching_tab), QtGui.QApplication.translate("PoliceDB", "Suspect Matching", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PoliceDB", "Understanding Hopfield", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("PoliceDB", "Trained Patterns", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("PoliceDB", "Draw Here!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("PoliceDB", "Convergance Chain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("PoliceDB", "<html><head/><body><p><span style=\" font-size:14pt;\">How it works</span></p><p><span style=\" font-size:8pt;\">The Hopfiled network used to converge this pattern is trained based on the<br/></span><span style=\" font-size:8pt; font-weight:600;\">Hebbian rule</span><span style=\" font-size:8pt;\">, which says that neurons that </span><span style=\" font-size:8pt; font-weight:600;\">fire together, wire together</span><span style=\" font-size:8pt;\">.</span></p><p><span style=\" font-size:8pt;\">In the context of images, neurons are black/white pixels.</span></p><p><span style=\" font-size:8pt;\">Based on this rule, a fully connected neural network is </span><span style=\" font-size:8pt; font-weight:600;\">trained</span><span style=\" font-size:8pt;\"> from<br/>the patterns to learn.</span></p><p><span style=\" font-size:8pt;\">When run against a pattern, random pixels are updated to the sign of<br/>their </span><span style=\" font-size:8pt; font-weight:600;\">weighted neighbours</span><span style=\" font-size:8pt;\"> until it </span><span style=\" font-size:8pt; font-weight:600;\">converges</span><span style=\" font-size:8pt;\">.<br/>With high probability the converged pattern will be one of the trained ones.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hopfiel_playground_tab), QtGui.QApplication.translate("PoliceDB", "Understanding Hopfield", None, QtGui.QApplication.UnicodeUTF8))
