# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'policedb.ui'
#
# Created: Thu Jan 10 11:52:19 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_PoliceDB(object):
    def setupUi(self, PoliceDB):
        PoliceDB.setObjectName("PoliceDB")
        PoliceDB.resize(849, 599)
        self.centralWidget = QtGui.QWidget(PoliceDB)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(40, 40))
        self.tabWidget.setObjectName("tabWidget")
        self.suspect_database_tab = QtGui.QWidget()
        self.suspect_database_tab.setObjectName("suspect_database_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.suspect_database_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.suspect_database_tab)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(48)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lhs = QtGui.QVBoxLayout()
        self.lhs.setObjectName("lhs")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtGui.QLabel(self.suspect_database_tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.addNewButton = QtGui.QToolButton(self.suspect_database_tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNewButton.setIcon(icon)
        self.addNewButton.setIconSize(QtCore.QSize(42, 42))
        self.addNewButton.setAutoRaise(True)
        self.addNewButton.setObjectName("addNewButton")
        self.horizontalLayout.addWidget(self.addNewButton)
        self.saveButton = QtGui.QToolButton(self.suspect_database_tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setIconSize(QtCore.QSize(42, 42))
        self.saveButton.setAutoRaise(True)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.loadButton = QtGui.QToolButton(self.suspect_database_tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadButton.setIcon(icon2)
        self.loadButton.setIconSize(QtCore.QSize(42, 42))
        self.loadButton.setAutoRaise(True)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.lhs.addLayout(self.horizontalLayout)
        self.imageList = QtGui.QListWidget(self.suspect_database_tab)
        self.imageList.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.imageList.setMovement(QtGui.QListView.Free)
        self.imageList.setResizeMode(QtGui.QListView.Adjust)
        self.imageList.setLayoutMode(QtGui.QListView.Batched)
        self.imageList.setViewMode(QtGui.QListView.IconMode)
        self.imageList.setUniformItemSizes(True)
        self.imageList.setWordWrap(True)
        self.imageList.setObjectName("imageList")
        self.lhs.addWidget(self.imageList)
        self.horizontalLayout_2.addLayout(self.lhs)
        self.rhs = QtGui.QGroupBox(self.suspect_database_tab)
        self.rhs.setObjectName("rhs")
        self.gridLayout = QtGui.QGridLayout(self.rhs)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.rhs)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.nameLabel = QtGui.QLabel(self.rhs)
        self.nameLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_3.addWidget(self.nameLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_31 = QtGui.QLabel(self.rhs)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_4.addWidget(self.label_31)
        self.ageLabel = QtGui.QLabel(self.rhs)
        self.ageLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ageLabel.setObjectName("ageLabel")
        self.horizontalLayout_4.addWidget(self.ageLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_32 = QtGui.QLabel(self.rhs)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.descLabel = QtGui.QTextBrowser(self.rhs)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.descLabel.setPalette(palette)
        self.descLabel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout_3.addWidget(self.descLabel)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.imageLabel = QtGui.QLabel(self.rhs)
        self.imageLabel.setMinimumSize(QtCore.QSize(201, 201))
        self.imageLabel.setMaximumSize(QtCore.QSize(251, 241))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/new/prefix1/lucasss.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.rhs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.suspect_database_tab)
        self.line.setAcceptDrops(False)
        self.line.setAutoFillBackground(False)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.tabWidget.addTab(self.suspect_database_tab, "")
        self.suspect_matching_tab = QtGui.QWidget()
        self.suspect_matching_tab.setObjectName("suspect_matching_tab")
        self.label_4 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(48)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_2 = QtGui.QFrame(self.suspect_matching_tab)
        self.line_2.setGeometry(QtCore.QRect(0, 80, 521, 16))
        self.line_2.setAcceptDrops(False)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_5.setGeometry(QtCore.QRect(745, -40, 78, 720))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/new/prefix1/vert2.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalScrollBar_2 = QtGui.QScrollBar(self.suspect_matching_tab)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(730, 0, 16, 591))
        self.verticalScrollBar_2.setMinimum(0)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.groupBox_4 = QtGui.QGroupBox(self.suspect_matching_tab)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 100, 321, 331))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 301, 301))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/new/prefix1/mugchar.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.groupBox_5 = QtGui.QGroupBox(self.suspect_matching_tab)
        self.groupBox_5.setGeometry(QtCore.QRect(380, 100, 321, 331))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 301, 301))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/new/prefix1/celeb.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_12 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_12.setGeometry(QtCore.QRect(170, 450, 101, 101))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000000.bmp"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_13.setGeometry(QtCore.QRect(310, 450, 101, 101))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000060.bmp"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_14.setGeometry(QtCore.QRect(450, 450, 101, 101))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000160.bmp"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_15.setGeometry(QtCore.QRect(590, 450, 101, 101))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/new/prefix1/sheen-images/000225.bmp"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_11 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_11.setGeometry(QtCore.QRect(20, 490, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_16 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_16.setGeometry(QtCore.QRect(20, 460, 131, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.suspect_matching_tab)
        self.label_17.setGeometry(QtCore.QRect(20, 510, 121, 16))
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.suspect_matching_tab, "")
        self.hopfiel_playground_tab = QtGui.QWidget()
        self.hopfiel_playground_tab.setObjectName("hopfiel_playground_tab")
        self.label_8 = QtGui.QLabel(self.hopfiel_playground_tab)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 771, 81))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(48)
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_3 = QtGui.QFrame(self.hopfiel_playground_tab)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 521, 16))
        self.line_3.setAcceptDrops(False)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_6 = QtGui.QGroupBox(self.hopfiel_playground_tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 100, 791, 131))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 101, 101))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/smiley1.bmp.bmp"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtGui.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(280, 20, 101, 101))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/eleven.bmp.bmp"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(150, 20, 101, 101))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/plus.bmp.bmp"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(410, 20, 101, 101))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/house.bmp.bmp"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(540, 20, 101, 101))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/circle.bmp.bmp"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(670, 20, 101, 101))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-images/highres/squarecross.bmp.bmp"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.groupBox_7 = QtGui.QGroupBox(self.hopfiel_playground_tab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 240, 321, 311))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 291, 281))
        self.label_9.setCursor(QtCore.Qt.ArrowCursor)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/new/prefix1/drawn-circle.jpg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.groupBox_8 = QtGui.QGroupBox(self.hopfiel_playground_tab)
        self.groupBox_8.setGeometry(QtCore.QRect(340, 240, 461, 311))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_24 = QtGui.QLabel(self.groupBox_8)
        self.label_24.setGeometry(QtCore.QRect(20, 30, 61, 61))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000001.bmp.bmp"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(90, 30, 61, 61))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000004.bmp.bmp"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.groupBox_8)
        self.label_26.setGeometry(QtCore.QRect(160, 30, 61, 61))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000006.bmp.bmp"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(230, 30, 61, 61))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000008.bmp.bmp"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtGui.QLabel(self.groupBox_8)
        self.label_28.setGeometry(QtCore.QRect(300, 30, 61, 61))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000009.bmp.bmp"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtGui.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(370, 30, 61, 61))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap(":/new/prefix1/8x8-convergence/highres/000010.bmp.bmp"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtGui.QLabel(self.groupBox_8)
        self.label_30.setGeometry(QtCore.QRect(20, 90, 411, 221))
        self.label_30.setTextFormat(QtCore.Qt.RichText)
        self.label_30.setObjectName("label_30")
        self.tabWidget.addTab(self.hopfiel_playground_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        PoliceDB.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(PoliceDB)
        self.statusBar.setObjectName("statusBar")
        PoliceDB.setStatusBar(self.statusBar)

        self.retranslateUi(PoliceDB)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PoliceDB)

    def retranslateUi(self, PoliceDB):
        PoliceDB.setWindowTitle(QtGui.QApplication.translate("PoliceDB", "PoliceDB", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PoliceDB", "Suspect Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PoliceDB", "The following images are trained into the database:", None, QtGui.QApplication.UnicodeUTF8))
        self.addNewButton.setToolTip(QtGui.QApplication.translate("PoliceDB", "Add suspect", None, QtGui.QApplication.UnicodeUTF8))
        self.addNewButton.setText(QtGui.QApplication.translate("PoliceDB", "Add Suspect", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setToolTip(QtGui.QApplication.translate("PoliceDB", "<html><head/><body><p>Save database</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("PoliceDB", "Save Database", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setToolTip(QtGui.QApplication.translate("PoliceDB", "<html><head/><body><p>Load database</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("PoliceDB", "Save Database", None, QtGui.QApplication.UnicodeUTF8))
        self.rhs.setTitle(QtGui.QApplication.translate("PoliceDB", "Selected suspect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PoliceDB", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("PoliceDB", "Lukas S.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("PoliceDB", "Age:", None, QtGui.QApplication.UnicodeUTF8))
        self.ageLabel.setText(QtGui.QApplication.translate("PoliceDB", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("PoliceDB", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.descLabel.setHtml(QtGui.QApplication.translate("PoliceDB", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica LT Std Light\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:14px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans\'; font-size:11px; color:#000000;\">Slim shady</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.suspect_database_tab), QtGui.QApplication.translate("PoliceDB", "Suspect Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PoliceDB", "Suspect Matching", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PoliceDB", "Input image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PoliceDB", "Best matching image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PoliceDB", "of", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("PoliceDB", "Convergence chain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("PoliceDB", "Hopfield model:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.suspect_matching_tab), QtGui.QApplication.translate("PoliceDB", "Suspect Matching", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PoliceDB", "Understanding Hopfield", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("PoliceDB", "Trained Patterns", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("PoliceDB", "Draw Here!", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("PoliceDB", "Convergance Chain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("PoliceDB", "<html><head/><body><p><span style=\" font-size:14pt;\">How it works</span></p><p><span style=\" font-size:8pt;\">The Hopfiled network used to converge this pattern is trained based on the<br/></span><span style=\" font-size:8pt; font-weight:600;\">Hebbian rule</span><span style=\" font-size:8pt;\">, which says that neurons that </span><span style=\" font-size:8pt; font-weight:600;\">fire together, wire together</span><span style=\" font-size:8pt;\">.</span></p><p><span style=\" font-size:8pt;\">In the context of images, neurons are black/white pixels.</span></p><p><span style=\" font-size:8pt;\">Based on this rule, a fully connected neural network is </span><span style=\" font-size:8pt; font-weight:600;\">trained</span><span style=\" font-size:8pt;\"> from<br/>the patterns to learn.</span></p><p><span style=\" font-size:8pt;\">When run against a pattern, random pixels are updated to the sign of<br/>their </span><span style=\" font-size:8pt; font-weight:600;\">weighted neighbours</span><span style=\" font-size:8pt;\"> until it </span><span style=\" font-size:8pt; font-weight:600;\">converges</span><span style=\" font-size:8pt;\">.<br/>With high probability the converged pattern will be one of the trained ones.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hopfiel_playground_tab), QtGui.QApplication.translate("PoliceDB", "Understanding Hopfield", None, QtGui.QApplication.UnicodeUTF8))

import policedbresource_rc
